import type { SkuComponent } from '@shared/schema';

export type UpgradeSeedEntry = {
  id: string;
  name: string;
  category: string;
  description: string;
  price: number;
  images: string[];
  parentId: string | null;
  variantName: string | null;
  published: boolean;
  popular?: boolean;
  sku: string;
  skuComponents?: SkuComponent[];
};

export const upgradeCatalog: UpgradeSeedEntry[] = [
  // Accessories Parent (for variations)
  {
    id: "accessories-parent",
    name: "Accessories",
    category: "equipment",
    description: "Choose your equipment package - Maxi Euro 8 with T5000/T6000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: null,
    variantName: null,
    published: false,
    sku: "MTV-EQP-000",
  },
  {
    id: "accessories-pack-1",
    name: "Accessories Pack 1",
    category: "equipment",
    description: "Maxi Euro 8 with T5000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 1 - Maxi Euro 8 with T5000 Pro & Mini Spin",
    published: true,
    sku: "MTV-EQP-001",
    skuComponents: [
      { sku: "MTV-EQP-EURO8-MAXI", description: "Maxi Euro 8 Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-T5000", description: "T5000 Pro Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-MSPIN", description: "Mini Spin Wheel Balancer", quantity: 1 },
    ],
  },
  {
    id: "accessories-pack-2",
    name: "Accessories Pack 2",
    category: "equipment",
    description: "Euro 8 with T5000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 2 - Euro 8 with T5000 Pro & Mini Spin",
    published: true,
    sku: "MTV-EQP-002",
    skuComponents: [
      { sku: "MTV-EQP-EURO8-STD", description: "Standard Euro 8 Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-T5000", description: "T5000 Pro Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-MSPIN", description: "Mini Spin Wheel Balancer", quantity: 1 },
    ],
  },
  {
    id: "accessories-pack-3",
    name: "Accessories Pack 3",
    category: "equipment",
    description: "Mini Euro 8 with T5000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 3 - Mini Euro 8 with T5000 Pro & Mini Spin",
    published: true,
    sku: "MTV-EQP-003",
    skuComponents: [
      { sku: "MTV-EQP-EURO8-MINI", description: "Mini Euro 8 Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-T5000", description: "T5000 Pro Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-MSPIN", description: "Mini Spin Wheel Balancer", quantity: 1 },
    ],
  },
  {
    id: "accessories-pack-4",
    name: "Accessories Pack 4",
    category: "equipment",
    description: "Maxi Euro 8 with T6000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 4 - Maxi Euro 8 with T6000 Pro & Mini Spin",
    published: true,
    sku: "MTV-EQP-004",
    skuComponents: [
      { sku: "MTV-EQP-EURO8-MAXI", description: "Maxi Euro 8 Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-T6000", description: "T6000 Pro Tyre Changer", quantity: 1 },
      { sku: "MTV-EQP-MSPIN", description: "Mini Spin Wheel Balancer", quantity: 1 },
    ],
  },

  // Air System Upgrades
  {
    id: "mounted-pto-air-system",
    name: "Mounted PTO Air System Upgrade",
    category: "air-systems",
    description: "Professional air system for mobile tyre fitting vehicles. We compound, powerful design for truly engineered for integrated into commercial vehicles",
    price: 449500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-AIR-001",
  },
  {
    id: "compressor-12hp-270l",
    name: "Compressor Upgrade To 12hp 270 Litre Electric Start",
    category: "air-systems",
    description: "HEAVY DUTY compressor pump only",
    price: 100000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    popular: true,
    sku: "MTV-AIR-002",
  },
  {
    id: "air-reel-fini",
    name: "Fini 9 meter Air Reel With Built In Compressor",
    category: "air-systems",
    description: "Professional 9 meter air reel with built-in compressor",
    price: 54500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-AIR-003",
  },
  {
    id: "compressor-reel-16m",
    name: "16m Compressor Reel",
    category: "air-systems",
    description: "Keep your air line well and out Kay. With our compressor reel",
    price: 17500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-AIR-004",
  },

  // Equipment
  {
    id: "super-spin-upgrade",
    name: "Upgrade to Super Spin auto spin wheel balancer",
    category: "equipment",
    description: "",
    price: 45000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-EQP-005",
  },

  // Branding
  {
    id: "full-revalco-wrap",
    name: "Full Revalco Wrap",
    category: "branding",
    description: "Give your van kerb appeal by having blowable full van wrap (LWB / MWB available)",
    price: 320000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-001",
  },
  {
    id: "half-wrap",
    name: "Half Wrap",
    category: "branding",
    description: "Give your van the WOW factor with a half wrap",
    price: 180000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-002",
  },
  {
    id: "graphic-pack",
    name: "Graphic Pack",
    category: "branding",
    description: "Add vehicle graphic pack (printed places on scores and rear, text on doors and rear sound)",
    price: 100000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-003",
  },
  {
    id: "rear-chapter-livery",
    name: "Rear Chapter & Livery",
    category: "branding",
    description: "Make sure you are aware at the back of the road with our fluorescent yellow day chapter & kit",
    price: 45000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-004",
  },
  {
    id: "branded-website",
    name: "Branded Website",
    category: "branding",
    description: "Have your very own branded website. Price is £1050+vat depending on your specification",
    price: 105000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-005",
  },
  {
    id: "full-print-package",
    name: "Full Print Package",
    category: "branding",
    description: "500 Business cards, 250 Leaflets, 5 Social media setup (Max 2 platforms)",
    price: 55000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-006",
    skuComponents: [
      { sku: "MTV-BRD-BCARD-500", description: "Business Cards x500", quantity: 1 },
      { sku: "MTV-BRD-LEAF-250", description: "Leaflets x250", quantity: 1 },
      { sku: "MTV-BRD-SOCIAL-2", description: "Social Media Setup (up to 2 platforms)", quantity: 1 },
    ],
  },
  {
    id: "garage-branding",
    name: "Garage Branding (Member of team will contact you for pricing)",
    category: "branding",
    description: "Reactivate branding: Graphic signage, Pivot, A Boards, banners",
    price: 1,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BRD-007",
  },

  // Van Interior Walls (with variations)
  {
    id: "van-interior-walls-parent",
    name: "Van Interior Walls",
    category: "comfort",
    description: "Line the interior of your van with white coating to protect your van",
    price: 160000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-CMF-000",
  },
  {
    id: "van-interior-diamond-lwb-standard",
    name: "Van Interior Walls - Diamond Liner LWB Standard",
    category: "comfort",
    description: "Line the interior of your van with white coating to protect your van",
    price: 160000,
    images: [],
    parentId: "van-interior-walls-parent",
    variantName: "Diamond Liner - LWB Standard",
    published: true,
    sku: "MTV-CMF-001",
  },
  {
    id: "van-interior-diamond-lwb-branded",
    name: "Van Interior Walls - Diamond Liner LWB Branded",
    category: "comfort",
    description: "Line the interior of your van with white coating to protect your van - with branding",
    price: 160000,
    images: [],
    parentId: "van-interior-walls-parent",
    variantName: "Diamond Liner - LWB Branded",
    published: true,
    sku: "MTV-CMF-002",
  },

  // Security
  {
    id: "van-cctv-system",
    name: "Van Online CCTV/NVR System",
    category: "security",
    description: "Add extra security and peace of mind to your van with our online / offline CCTV system",
    price: 220000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-SEC-001",
  },
  {
    id: "vehicle-immobiliser",
    name: "Vehicle Immobiliser",
    category: "security",
    description: "Most advanced vehicle immobiliser on the market to protect your business asset",
    price: 50000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-SEC-002",
  },
  {
    id: "vehicle-tracker",
    name: "Vehicle tracker",
    category: "security",
    description: "With App to track your vehicle",
    price: 35000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-SEC-003",
  },
  {
    id: "high-security-door-lock",
    name: "High Security Door Lock",
    category: "security",
    description: "Add extra security to your van with our high security locks",
    price: 19500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-SEC-004",
  },
  {
    id: "standard-reversing-camera",
    name: "Standard Reversing Camera Kit",
    category: "security",
    description: "Standard reversing camera with 7\" monitor",
    price: 49500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-SEC-005",
    skuComponents: [
      { sku: "MTV-SEC-CAM-REV", description: "Reversing Camera", quantity: 1 },
      { sku: "MTV-TEC-MON-7IN", description: "7\" Monitor", quantity: 1 },
    ],
  },

  // Business
  {
    id: "business-package",
    name: "All you need business package",
    category: "business",
    description: "Website, Business cards, Leaflets, & Social media setup (Max 2 platforms)",
    price: 195000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-BIZ-001",
    skuComponents: [
      { sku: "MTV-BRD-005", description: "Branded Website", quantity: 1 },
      { sku: "MTV-BRD-BCARD-500", description: "Business Cards x500", quantity: 1 },
      { sku: "MTV-BRD-LEAF-250", description: "Leaflets x250", quantity: 1 },
      { sku: "MTV-BRD-SOCIAL-2", description: "Social Media Setup (up to 2 platforms)", quantity: 1 },
    ],
  },

  // Lighting Parent (with variations)
  {
    id: "light-pack-parent",
    name: "Light Pack",
    category: "lighting",
    description: "8 LED flashing repeaters, LED light bar to roof & working lights. With the optional upgrade you get LED scene lights",
    price: 120000,
    images: [],
    parentId: null,
    variantName: null,
    published: false,
    sku: "MTV-LGT-000",
  },
  {
    id: "light-pack-standard",
    name: "Standard Light Pack",
    category: "lighting",
    description: "8 LED flashing repeaters, LED light bar to roof & working lights",
    price: 120000,
    images: [],
    parentId: "light-pack-parent",
    variantName: "Standard Light Pack",
    published: true,
    sku: "MTV-LGT-001",
    skuComponents: [
      { sku: "MTV-LGT-REPEATER-LED", description: "LED Flashing Repeater", quantity: 8 },
      { sku: "MTV-LGT-BAR-ROOF", description: "LED Light Bar (Roof)", quantity: 1 },
      { sku: "MTV-LGT-WORK-LED", description: "LED Working Light", quantity: 1 },
    ],
  },
  {
    id: "light-pack-upgraded",
    name: "Upgraded Light Pack",
    category: "lighting",
    description: "8 LED flashing repeaters, LED light bar to roof & working lights to side and rear of van. Upgraded to LED scene lights with side marker lights to side and rear",
    price: 170000,
    images: [],
    parentId: "light-pack-parent",
    variantName: "Upgraded Light Pack - LED Scene Lights",
    published: true,
    sku: "MTV-LGT-002",
    skuComponents: [
      { sku: "MTV-LGT-REPEATER-LED", description: "LED Flashing Repeater", quantity: 8 },
      { sku: "MTV-LGT-BAR-ROOF", description: "LED Light Bar (Roof)", quantity: 1 },
      { sku: "MTV-LGT-WORK-LED", description: "LED Working Light", quantity: 1 },
      { sku: "MTV-LGT-SCENE-LED", description: "LED Scene Light", quantity: 1 },
      { sku: "MTV-LGT-MARKER-SIDE", description: "Side Marker Light", quantity: 2 },
    ],
  },

  // Technology
  {
    id: "remote-control",
    name: "Remote Control",
    category: "technology",
    description: "Control all of your vans accessories with our wireless remote system",
    price: 69500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-TEC-001",
  },
  {
    id: "monitor-brake-light-camera",
    name: "7\" Monitor With Brake Light Camera",
    category: "technology",
    description: "In cab 'plant' device always recording when driving",
    price: 49500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-TEC-002",
    skuComponents: [
      { sku: "MTV-TEC-MON-7IN", description: "7\" In-Cab Monitor", quantity: 1 },
      { sku: "MTV-TEC-CAM-BRAKE", description: "Brake Light Camera", quantity: 1 },
    ],
  },
  {
    id: "apple-carplay",
    name: "Apple CarPlay",
    category: "technology",
    description: "Apple CarPlay or Android Auto (vehicle dependent, starting from £650+vat, a member of our team will confirm that your ice vehicle package right, once order is placed)",
    price: 65000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-TEC-003",
  },
  {
    id: "front-facing-dash-camera",
    name: "Front Facing Dash Camera",
    category: "technology",
    description: "In cab 'plant' device always recording when driving",
    price: 35000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    sku: "MTV-TEC-004",
  },

  // Comfort Parent (Carpeted Ceiling with variations)
  {
    id: "carpeted-ceiling-parent",
    name: "Carpeted Ceiling",
    category: "comfort",
    description: "Carpeted ceiling for your van",
    price: 68500,
    images: [],
    parentId: null,
    variantName: null,
    published: false,
    sku: "MTV-CMF-010",
  },
  {
    id: "carpeted-ceiling-lwb-led",
    name: "Carpeted Ceiling LWB with LED cabin lights",
    category: "comfort",
    description: "",
    price: 68500,
    images: [],
    parentId: "carpeted-ceiling-parent",
    variantName: "LWB with LED cabin lights",
    published: true,
    sku: "MTV-CMF-011",
    skuComponents: [
      { sku: "MTV-CMF-CARPET-LWB", description: "Carpeted Ceiling (LWB)", quantity: 1 },
      { sku: "MTV-LGT-CABIN-LED", description: "LED Cabin Light", quantity: 1 },
    ],
  },
];
