import OpenAI from "openai";
import { storage } from "./storage";

const BLOG_KEYWORDS = [
  "how to start a mobile tyre fitting business UK",
  "mobile tyre fitting van equipment list UK",
  "how much does a mobile tyre fitting business make",
  "REACT motorway certification UK tyre fitter",
  "mobile tyre van conversion cost UK",
  "best van for mobile tyre fitting business UK",
  "mobile tyre fitting business insurance UK",
  "how to get customers for mobile tyre fitting business",
  "mobile tyre fitting vs tyre shop which is more profitable",
  "VW Crafter mobile tyre van conversion UK",
  "Ford Transit mobile tyre van setup UK",
  "how to finance a mobile tyre van UK",
  "mobile tyre fitting business plan UK",
  "TPMS diagnostics mobile tyre fitter",
  "mobile tyre fitting business startup costs UK 2026",
  "mobile tyre fitting franchise vs independent UK",
  "tyre fitting van fit out checklist UK",
  "electric van mobile tyre business UK",
  "mobile tyre van income potential UK",
  "how to price mobile tyre fitting jobs UK",
];

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

async function getNextKeyword(): Promise<string> {
  try {
    const posts = await storage.getBlogPostsAdmin();
    const autoGenerated = posts.filter(
      (p) => Array.isArray(p.tags) && p.tags.includes("auto-generated")
    );
    const usedKeywords = autoGenerated
      .map((p) => {
        const kw = (p.tags as string[]).find((t) => t.startsWith("keyword:"));
        return kw ? kw.replace("keyword:", "") : null;
      })
      .filter(Boolean) as string[];

    const unused = BLOG_KEYWORDS.filter((k) => !usedKeywords.includes(k));
    if (unused.length === 0) {
      return BLOG_KEYWORDS[autoGenerated.length % BLOG_KEYWORDS.length];
    }
    return unused[0];
  } catch {
    return BLOG_KEYWORDS[0];
  }
}

export async function generateAiBlogPost(
  customKeyword: string | null = null,
  saveAsDraft = true
) {
  const openaiApiKey = process.env.AI_INTEGRATIONS_OPENAI_API_KEY;
  const openaiBaseUrl = process.env.AI_INTEGRATIONS_OPENAI_BASE_URL;

  if (!openaiApiKey) {
    throw new Error("OpenAI API key not configured");
  }

  const keyword = customKeyword || (await getNextKeyword());
  console.log(`[Blog AI] Generating post for keyword: "${keyword}"`);

  const client = new OpenAI({
    apiKey: openaiApiKey,
    ...(openaiBaseUrl ? { baseURL: openaiBaseUrl } : {}),
  });

  const systemPrompt = `You are an expert SEO content writer for Mobile Tyre Vans, a UK company based in the UK (AA1 1AA) that builds and sells professionally converted mobile tyre fitting vans. The business offers custom van conversions, van finance (FCA authorised), tyre supplier connections, and REACT motorway training.

Write high-quality, SEO-optimised blog posts that:
- Are genuinely helpful and informative for people considering starting a mobile tyre fitting business
- Naturally position Mobile Tyre Vans as the go-to solution
- Include the target keyword naturally in the title, introduction, and throughout the body
- Are written in British English
- Are between 900 and 1,200 words
- End with a strong call to action mentioning the phone number 0800 000 0000

IMPORTANT: Return ONLY a valid JSON object with exactly these fields:
{
  "title": "The H1 blog post title (engaging, keyword-rich)",
  "summary": "A 2-sentence teaser for the post listing page (max 200 chars)",
  "content": "The full blog post body in plain HTML using only <h2>, <p>, <strong>, <ul>, <li>, <a> tags",
  "seoTitle": "Custom page title for search engines (max 60 chars)",
  "seoDescription": "Meta description for search engines (max 155 chars)"
}`;

  const response = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: systemPrompt },
      {
        role: "user",
        content: `Write a complete SEO blog post targeting the keyword: "${keyword}"`,
      },
    ],
    temperature: 0.7,
    response_format: { type: "json_object" },
  });

  const raw = response.choices[0].message.content;
  if (!raw) throw new Error("OpenAI returned empty response");

  const parsed = JSON.parse(raw);

  if (!parsed.title || !parsed.summary || !parsed.content) {
    throw new Error("OpenAI response missing required fields");
  }

  const baseSlug = slugify(parsed.title);
  let slug = baseSlug;
  let attempt = 0;
  while (true) {
    const existing = await storage.getBlogPostBySlug(slug).catch(() => null);
    if (!existing) break;
    attempt++;
    slug = `${baseSlug}-${attempt}`;
  }

  const post = await storage.createBlogPost({
    title: parsed.title,
    slug,
    summary: parsed.summary,
    content: parsed.content,
    seoTitle: parsed.seoTitle || null,
    seoDescription: parsed.seoDescription || null,
    authorName: "MTV Team",
    category: "Business Tips",
    tags: ["auto-generated", `keyword:${keyword}`],
    published: !saveAsDraft,
    publishedAt: saveAsDraft ? null : new Date(),
    featuredImage: null,
  });

  console.log(`[Blog AI] Post created: "${post.title}" (slug: ${post.slug})`);
  return post;
}

export { BLOG_KEYWORDS };
